dataset:
  img_size: 64
  name: FAKEDATA
  num_classes: 10
  num_workers: 2
model:
  adanpc:
    beta: 0.99
    delta: 0.1
    micro_steps: 4
  name: resnet18
  pretrained: false
  tta: adanpc
  variant: full
optimizer:
  lr: 0.01
  momentum: 0.9
  name: SGD
run_id: AdaNPC-full_fake
training:
  batch_size: 32
  epochs: 1
