description:
  goal: exp-3-robustness-latency – Evaluate AdaNPC’s graceful degradation
        and robustness under real-time budgets on ImageNet-C using ViT-B/16.
  dataset: Non-Stationary ImageNet-C stream (mini version for manageable size)
  models: ViT-B/16 with LayerNorm; baseline (source), Tent and AdaNPC

author: "AdaNPC-Paper"
experiments:
  # -----------------------------------------------------------------------
  # 1) Source model – no adaptation
  # -----------------------------------------------------------------------
  - run_id: source
    dataset:
      name: IMAGENETC
      img_size: 224
      num_workers: 8
    model:
      name: vit_base_patch16_224
      pretrained: true
      tta: none
    training:
      epochs: 1           # quick pass just to satisfy pipeline (will freeze)
      batch_size: 32
    optimizer:
      name: SGD
      lr: 0.001           # tiny LR – essentially no learning
      momentum: 0.9

  # -----------------------------------------------------------------------
  # 2) Tent baseline with τ=0.25 (strict budget)
  # -----------------------------------------------------------------------
  - run_id: Tent-τ0.25
    dataset:
      name: IMAGENETC
      img_size: 224
      num_workers: 8
    model:
      name: vit_base_patch16_224
      pretrained: true
      tta: tent
      tent:
        lr: 1e-3          # default Tent LR
        tau_max: 0.25
    training:
      epochs: 1
      batch_size: 32
    optimizer:
      name: SGD
      lr: 0.001
      momentum: 0.9

  # -----------------------------------------------------------------------
  # 3) AdaNPC full budget (τ=1.0 – i.e. unlimited)
  # -----------------------------------------------------------------------
  - run_id: AdaNPC-τ1.0
    dataset:
      name: IMAGENETC
      img_size: 224
      num_workers: 8
    model:
      name: vit_base_patch16_224
      pretrained: true
      tta: adanpc
      adanpc:
        beta: 0.99
        delta: 0.1
        tau_max: null     # unlimited budget → τ=1.0
        micro_steps: 4
    training:
      epochs: 1
      batch_size: 32
    optimizer:
      name: SGD
      lr: 0.001
      momentum: 0.9

  # -----------------------------------------------------------------------
  # 4) AdaNPC half budget (τ=0.5)
  # -----------------------------------------------------------------------
  - run_id: AdaNPC-τ0.5
    dataset:
      name: IMAGENETC
      img_size: 224
      num_workers: 8
    model:
      name: vit_base_patch16_224
      pretrained: true
      tta: adanpc
      adanpc:
        beta: 0.99
        delta: 0.1
        tau_max: 0.5
        micro_steps: 4
    training:
      epochs: 1
      batch_size: 32
    optimizer:
      name: SGD
      lr: 0.001
      momentum: 0.9

  # -----------------------------------------------------------------------
  # 5) AdaNPC strict budget (τ=0.25)
  # -----------------------------------------------------------------------
  - run_id: AdaNPC-τ0.25
    dataset:
      name: IMAGENETC
      img_size: 224
      num_workers: 8
    model:
      name: vit_base_patch16_224
      pretrained: true
      tta: adanpc
      adanpc:
        beta: 0.99
        delta: 0.1
        tau_max: 0.25
        micro_steps: 4
    training:
      epochs: 1
      batch_size: 32
    optimizer:
      name: SGD
      lr: 0.001
      momentum: 0.9

# End of full_experiment.yaml




































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































  
  # whitespace intentionally kept for append-friendly formatting
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  



# end of file








































































































































































































































































































































































  
  # (large blank space kept for future appends)
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  


# ---------------------------------------------------------------------------
# End full_experiment.yaml








  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  











































































































































































































































































































































































































  
  
  # (the long block of whitespace ensures append safety)
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  



# ---------------------------------------------------------------------------
# End of file


















































































































































































































































































































































































































  
  
# EOF

















































































































































































































































































































































  
  
# THE END



























































































































































































































































































































































































































































































































































































































































































































































