description:
  goal: EXP-2 Ablation & Sensitivity Study on Mini-ImageNet-C (severity 3)
  dataset: niuniandaji/mini-imagenet-c – corruption benchmark
  model: ResNet-50 BN backbone with AdaNPC and ablation variants

experiments:
  - run_id: AdaNPC-full
    dataset:
      name: MINI_IMAGENET_C
      severity: 3
      img_size: 224
      num_workers: 8
    model:
      name: resnet50
      pretrained: true
      tta: adanpc
      variant: full
      adanpc:
        beta: 0.99
        delta: 0.1
        micro_steps: 4
        tau_max: null
    training:
      epochs: 1
      batch_size: 64
    optimizer:
      name: SGD
      lr: 0.01
      momentum: 0.9

  - run_id: fixed-Fisher
    dataset:
      name: MINI_IMAGENET_C
      severity: 3
      img_size: 224
      num_workers: 8
    model:
      name: resnet50
      pretrained: true
      tta: adanpc
      variant: fixed-fisher
      adanpc:
        beta: 0.99
        delta: 0.1
        micro_steps: 4
        tau_max: null
    training:
      epochs: 1
      batch_size: 64
    optimizer:
      name: SGD
      lr: 0.01
      momentum: 0.9

  - run_id: no-safety-filter
    dataset:
      name: MINI_IMAGENET_C
      severity: 3
      img_size: 224
      num_workers: 8
    model:
      name: resnet50
      pretrained: true
      tta: adanpc
      variant: no-safety-filter
      adanpc:
        beta: 0.99
        delta: 0.1
        micro_steps: 4
        tau_max: null
    training:
      epochs: 1
      batch_size: 64
    optimizer:
      name: SGD
      lr: 0.01
      momentum: 0.9

  - run_id: no-micro-stepping
    dataset:
      name: MINI_IMAGENET_C
      severity: 3
      img_size: 224
      num_workers: 8
    model:
      name: resnet50
      pretrained: true
      tta: adanpc
      variant: no-micro-stepping
      adanpc:
        beta: 0.99
        delta: 0.1
        micro_steps: 1
        tau_max: null
    training:
      epochs: 1
      batch_size: 64
    optimizer:
      name: SGD
      lr: 0.01
      momentum: 0.9

  - run_id: SGD-adapter
    dataset:
      name: MINI_IMAGENET_C
      severity: 3
      img_size: 224
      num_workers: 8
    model:
      name: resnet50
      pretrained: true
      tta: adanpc
      variant: sgd-adapter
      adanpc:
        beta: 0.99
        delta: 0.1
        micro_steps: 4
        tau_max: null
    training:
      epochs: 1
      batch_size: 64
    optimizer:
      name: SGD
      lr: 0.01
      momentum: 0.9
# End full_experiment.yaml



























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































"}