dataset:
  img_size: 64
  name: FAKEDATA
  num_classes: 10
  num_workers: 2
model:
  name: resnet18
  pretrained: false
  tent:
    lr: 1e-3
    tau_max: 0.25
  tta: tent
optimizer:
  lr: 0.01
  momentum: 0.9
  name: SGD
run_id: tent_tau0.25_fake
training:
  batch_size: 32
  epochs: 1
